### ISSUE TITLE
payment problems

### ISSUE THREAD

**Issue by J1mmyV** [val92130/Supreme-Auto-Checkout#69]
Hey,
I've tried to use the bot in the last 3 drops but I didn't manage to cop anything. Everytime the bot put the item in basket, then it went to the checkout page, autofilled everything, waited 2,5 seconds (as I set in options) and then it was supposed to auto pay, but everytime the site displayed the 'Unfortunately, we cannot proceed your payment...' page. Am I doing something wrong?

I'll attach the screens of the last drop's settings I've used

![ss2](https://user-images.githubusercontent.com/32311058/32066055-e234b232-ba7e-11e7-91d7-1101dd10803c.png)
![ss3](https://user-images.githubusercontent.com/32311058/32066056-e24fc482-ba7e-11e7-9367-b145941c9a6b.png)
![ss4](https://user-images.githubusercontent.com/32311058/32066057-e271cfc8-ba7e-11e7-810f-aae73527ed36.png)
![ss1](https://user-images.githubusercontent.com/32311058/32066058-e28fabd8-ba7e-11e7-88c8-9a4b85158ea4.png)

Thanks!

**Comment by val92130** [comment]
Hey! Thanks for reporting this, your bot is correctly configured, but unfortunately this issue is very common and is not related to the bot. 

There was a lot of card declined errors in the latest drops and it seems to happen whenever a product is sold out during your checkout process or because of the high traffic on the supreme website.

 It can also mean you have been banned by suprême but I highly doubt that. 
Your best bet to avoid that is to buy the item you want during a restock, usually a few minutes after the actual drop!
